# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.location import Location  # noqa: F401,E501
from swagger_server import util


class Body5(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_id: int=None, location: Location=None):  # noqa: E501
        """Body5 - a model defined in Swagger

        :param org_id: The org_id of this Body5.  # noqa: E501
        :type org_id: int
        :param location: The location of this Body5.  # noqa: E501
        :type location: Location
        """
        self.swagger_types = {
            'org_id': int,
            'location': Location
        }

        self.attribute_map = {
            'org_id': 'org_id',
            'location': 'location'
        }
        self._org_id = org_id
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'Body5':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_5 of this Body5.  # noqa: E501
        :rtype: Body5
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_id(self) -> int:
        """Gets the org_id of this Body5.

        The id of the org to add the location to  # noqa: E501

        :return: The org_id of this Body5.
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: int):
        """Sets the org_id of this Body5.

        The id of the org to add the location to  # noqa: E501

        :param org_id: The org_id of this Body5.
        :type org_id: int
        """

        self._org_id = org_id

    @property
    def location(self) -> Location:
        """Gets the location of this Body5.


        :return: The location of this Body5.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location: Location):
        """Sets the location of this Body5.


        :param location: The location of this Body5.
        :type location: Location
        """

        self._location = location
