# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body8(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_id: int=None):  # noqa: E501
        """Body8 - a model defined in Swagger

        :param org_id: The org_id of this Body8.  # noqa: E501
        :type org_id: int
        """
        self.swagger_types = {
            'org_id': int
        }

        self.attribute_map = {
            'org_id': 'org_id'
        }
        self._org_id = org_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body8':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_8 of this Body8.  # noqa: E501
        :rtype: Body8
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_id(self) -> int:
        """Gets the org_id of this Body8.

        The id of the org to get verifiers for  # noqa: E501

        :return: The org_id of this Body8.
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: int):
        """Sets the org_id of this Body8.

        The id of the org to get verifiers for  # noqa: E501

        :param org_id: The org_id of this Body8.
        :type org_id: int
        """

        self._org_id = org_id
