# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body10(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_id: int=None, election_id: int=None):  # noqa: E501
        """Body10 - a model defined in Swagger

        :param org_id: The org_id of this Body10.  # noqa: E501
        :type org_id: int
        :param election_id: The election_id of this Body10.  # noqa: E501
        :type election_id: int
        """
        self.swagger_types = {
            'org_id': int,
            'election_id': int
        }

        self.attribute_map = {
            'org_id': 'org_id',
            'election_id': 'election_id'
        }
        self._org_id = org_id
        self._election_id = election_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body10':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_10 of this Body10.  # noqa: E501
        :rtype: Body10
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_id(self) -> int:
        """Gets the org_id of this Body10.

        The id of the org to get the election for  # noqa: E501

        :return: The org_id of this Body10.
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: int):
        """Sets the org_id of this Body10.

        The id of the org to get the election for  # noqa: E501

        :param org_id: The org_id of this Body10.
        :type org_id: int
        """

        self._org_id = org_id

    @property
    def election_id(self) -> int:
        """Gets the election_id of this Body10.

        The id of the election to get  # noqa: E501

        :return: The election_id of this Body10.
        :rtype: int
        """
        return self._election_id

    @election_id.setter
    def election_id(self, election_id: int):
        """Sets the election_id of this Body10.

        The id of the election to get  # noqa: E501

        :param election_id: The election_id of this Body10.
        :type election_id: int
        """

        self._election_id = election_id
