# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body6(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, location_id: int=None):  # noqa: E501
        """Body6 - a model defined in Swagger

        :param location_id: The location_id of this Body6.  # noqa: E501
        :type location_id: int
        """
        self.swagger_types = {
            'location_id': int
        }

        self.attribute_map = {
            'location_id': 'location_id'
        }
        self._location_id = location_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body6':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_6 of this Body6.  # noqa: E501
        :rtype: Body6
        """
        return util.deserialize_model(dikt, cls)

    @property
    def location_id(self) -> int:
        """Gets the location_id of this Body6.

        The id of the location to delete  # noqa: E501

        :return: The location_id of this Body6.
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id: int):
        """Sets the location_id of this Body6.

        The id of the location to delete  # noqa: E501

        :param location_id: The location_id of this Body6.
        :type location_id: int
        """

        self._location_id = location_id
