# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, org_uid: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param name: The name of this Body.  # noqa: E501
        :type name: str
        :param org_uid: The org_uid of this Body.  # noqa: E501
        :type org_uid: str
        """
        self.swagger_types = {
            'name': str,
            'org_uid': str
        }

        self.attribute_map = {
            'name': 'name',
            'org_uid': 'org_uid'
        }
        self._name = name
        self._org_uid = org_uid

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Body.

        The name of the org being created  # noqa: E501

        :return: The name of this Body.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Body.

        The name of the org being created  # noqa: E501

        :param name: The name of this Body.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def org_uid(self) -> str:
        """Gets the org_uid of this Body.

        The id of the user within  # noqa: E501

        :return: The org_uid of this Body.
        :rtype: str
        """
        return self._org_uid

    @org_uid.setter
    def org_uid(self, org_uid: str):
        """Sets the org_uid of this Body.

        The id of the user within  # noqa: E501

        :param org_uid: The org_uid of this Body.
        :type org_uid: str
        """

        self._org_uid = org_uid
