# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_org import UserOrg  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, orgs: List[UserOrg]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param orgs: The orgs of this InlineResponse2002.  # noqa: E501
        :type orgs: List[UserOrg]
        """
        self.swagger_types = {
            'orgs': List[UserOrg]
        }

        self.attribute_map = {
            'orgs': 'orgs'
        }
        self._orgs = orgs

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def orgs(self) -> List[UserOrg]:
        """Gets the orgs of this InlineResponse2002.

        A list of all the orgs the user belongs to  # noqa: E501

        :return: The orgs of this InlineResponse2002.
        :rtype: List[UserOrg]
        """
        return self._orgs

    @orgs.setter
    def orgs(self, orgs: List[UserOrg]):
        """Sets the orgs of this InlineResponse2002.

        A list of all the orgs the user belongs to  # noqa: E501

        :param orgs: The orgs of this InlineResponse2002.
        :type orgs: List[UserOrg]
        """

        self._orgs = orgs
