# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rpi_id: int=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param rpi_id: The rpi_id of this InlineResponse2006.  # noqa: E501
        :type rpi_id: int
        """
        self.swagger_types = {
            'rpi_id': int
        }

        self.attribute_map = {
            'rpi_id': 'rpi_id'
        }
        self._rpi_id = rpi_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rpi_id(self) -> int:
        """Gets the rpi_id of this InlineResponse2006.

        The id of the RPI just added  # noqa: E501

        :return: The rpi_id of this InlineResponse2006.
        :rtype: int
        """
        return self._rpi_id

    @rpi_id.setter
    def rpi_id(self, rpi_id: int):
        """Sets the rpi_id of this InlineResponse2006.

        The id of the RPI just added  # noqa: E501

        :param rpi_id: The rpi_id of this InlineResponse2006.
        :type rpi_id: int
        """

        self._rpi_id = rpi_id
