# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.rpi import Rpi  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rpis: List[Rpi]=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param rpis: The rpis of this InlineResponse2005.  # noqa: E501
        :type rpis: List[Rpi]
        """
        self.swagger_types = {
            'rpis': List[Rpi]
        }

        self.attribute_map = {
            'rpis': 'rpis'
        }
        self._rpis = rpis

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rpis(self) -> List[Rpi]:
        """Gets the rpis of this InlineResponse2005.


        :return: The rpis of this InlineResponse2005.
        :rtype: List[Rpi]
        """
        return self._rpis

    @rpis.setter
    def rpis(self, rpis: List[Rpi]):
        """Sets the rpis of this InlineResponse2005.


        :param rpis: The rpis of this InlineResponse2005.
        :type rpis: List[Rpi]
        """

        self._rpis = rpis
