# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.org_user_invite import OrgUserInvite  # noqa: F401,E501
from swagger_server import util


class InlineResponse404(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, users: List[OrgUserInvite]=None):  # noqa: E501
        """InlineResponse404 - a model defined in Swagger

        :param users: The users of this InlineResponse404.  # noqa: E501
        :type users: List[OrgUserInvite]
        """
        self.swagger_types = {
            'users': List[OrgUserInvite]
        }

        self.attribute_map = {
            'users': 'users'
        }
        self._users = users

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse404':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_404 of this InlineResponse404.  # noqa: E501
        :rtype: InlineResponse404
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self) -> List[OrgUserInvite]:
        """Gets the users of this InlineResponse404.


        :return: The users of this InlineResponse404.
        :rtype: List[OrgUserInvite]
        """
        return self._users

    @users.setter
    def users(self, users: List[OrgUserInvite]):
        """Sets the users of this InlineResponse404.


        :param users: The users of this InlineResponse404.
        :type users: List[OrgUserInvite]
        """

        self._users = users
