# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.location import Location  # noqa: F401,E501
from swagger_server import util


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, locations: List[Location]=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger

        :param locations: The locations of this InlineResponse2007.  # noqa: E501
        :type locations: List[Location]
        """
        self.swagger_types = {
            'locations': List[Location]
        }

        self.attribute_map = {
            'locations': 'locations'
        }
        self._locations = locations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2007':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def locations(self) -> List[Location]:
        """Gets the locations of this InlineResponse2007.


        :return: The locations of this InlineResponse2007.
        :rtype: List[Location]
        """
        return self._locations

    @locations.setter
    def locations(self, locations: List[Location]):
        """Sets the locations of this InlineResponse2007.


        :param locations: The locations of this InlineResponse2007.
        :type locations: List[Location]
        """

        self._locations = locations
