# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse2008(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, verifiers: List[User]=None):  # noqa: E501
        """InlineResponse2008 - a model defined in Swagger

        :param verifiers: The verifiers of this InlineResponse2008.  # noqa: E501
        :type verifiers: List[User]
        """
        self.swagger_types = {
            'verifiers': List[User]
        }

        self.attribute_map = {
            'verifiers': 'verifiers'
        }
        self._verifiers = verifiers

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2008':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_8 of this InlineResponse2008.  # noqa: E501
        :rtype: InlineResponse2008
        """
        return util.deserialize_model(dikt, cls)

    @property
    def verifiers(self) -> List[User]:
        """Gets the verifiers of this InlineResponse2008.


        :return: The verifiers of this InlineResponse2008.
        :rtype: List[User]
        """
        return self._verifiers

    @verifiers.setter
    def verifiers(self, verifiers: List[User]):
        """Sets the verifiers of this InlineResponse2008.


        :param verifiers: The verifiers of this InlineResponse2008.
        :type verifiers: List[User]
        """

        self._verifiers = verifiers
