# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.election import Election  # noqa: F401,E501
from swagger_server import util


class InlineResponse2008(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, election: Election=None):  # noqa: E501
        """InlineResponse2008 - a model defined in Swagger

        :param election: The election of this InlineResponse2008.  # noqa: E501
        :type election: Election
        """
        self.swagger_types = {
            'election': Election
        }

        self.attribute_map = {
            'election': 'election'
        }
        self._election = election

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2008':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_8 of this InlineResponse2008.  # noqa: E501
        :rtype: InlineResponse2008
        """
        return util.deserialize_model(dikt, cls)

    @property
    def election(self) -> Election:
        """Gets the election of this InlineResponse2008.


        :return: The election of this InlineResponse2008.
        :rtype: Election
        """
        return self._election

    @election.setter
    def election(self, election: Election):
        """Sets the election of this InlineResponse2008.


        :param election: The election of this InlineResponse2008.
        :type election: Election
        """

        self._election = election
