# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_info: User=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param user_info: The user_info of this InlineResponse2001.  # noqa: E501
        :type user_info: User
        """
        self.swagger_types = {
            'user_info': User
        }

        self.attribute_map = {
            'user_info': 'user_info'
        }
        self._user_info = user_info

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_info(self) -> User:
        """Gets the user_info of this InlineResponse2001.


        :return: The user_info of this InlineResponse2001.
        :rtype: User
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info: User):
        """Sets the user_info of this InlineResponse2001.


        :param user_info: The user_info of this InlineResponse2001.
        :type user_info: User
        """

        self._user_info = user_info
