# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.location import Location  # noqa: F401,E501
from swagger_server import util


class Rpi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rpi_id: int=None, org_id: int=None, location: Location=None):  # noqa: E501
        """Rpi - a model defined in Swagger

        :param rpi_id: The rpi_id of this Rpi.  # noqa: E501
        :type rpi_id: int
        :param org_id: The org_id of this Rpi.  # noqa: E501
        :type org_id: int
        :param location: The location of this Rpi.  # noqa: E501
        :type location: Location
        """
        self.swagger_types = {
            'rpi_id': int,
            'org_id': int,
            'location': Location
        }

        self.attribute_map = {
            'rpi_id': 'rpi_id',
            'org_id': 'org_id',
            'location': 'location'
        }
        self._rpi_id = rpi_id
        self._org_id = org_id
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'Rpi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rpi of this Rpi.  # noqa: E501
        :rtype: Rpi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rpi_id(self) -> int:
        """Gets the rpi_id of this Rpi.


        :return: The rpi_id of this Rpi.
        :rtype: int
        """
        return self._rpi_id

    @rpi_id.setter
    def rpi_id(self, rpi_id: int):
        """Sets the rpi_id of this Rpi.


        :param rpi_id: The rpi_id of this Rpi.
        :type rpi_id: int
        """

        self._rpi_id = rpi_id

    @property
    def org_id(self) -> int:
        """Gets the org_id of this Rpi.

        Id of the owner org  # noqa: E501

        :return: The org_id of this Rpi.
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: int):
        """Sets the org_id of this Rpi.

        Id of the owner org  # noqa: E501

        :param org_id: The org_id of this Rpi.
        :type org_id: int
        """

        self._org_id = org_id

    @property
    def location(self) -> Location:
        """Gets the location of this Rpi.


        :return: The location of this Rpi.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location: Location):
        """Sets the location of this Rpi.


        :param location: The location of this Rpi.
        :type location: Location
        """

        self._location = location
