# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class Verifier(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_info: User=None, location_id: int=None):  # noqa: E501
        """Verifier - a model defined in Swagger

        :param user_info: The user_info of this Verifier.  # noqa: E501
        :type user_info: User
        :param location_id: The location_id of this Verifier.  # noqa: E501
        :type location_id: int
        """
        self.swagger_types = {
            'user_info': User,
            'location_id': int
        }

        self.attribute_map = {
            'user_info': 'user_info',
            'location_id': 'location_id'
        }
        self._user_info = user_info
        self._location_id = location_id

    @classmethod
    def from_dict(cls, dikt) -> 'Verifier':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The verifier of this Verifier.  # noqa: E501
        :rtype: Verifier
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_info(self) -> User:
        """Gets the user_info of this Verifier.


        :return: The user_info of this Verifier.
        :rtype: User
        """
        return self._user_info

    @user_info.setter
    def user_info(self, user_info: User):
        """Sets the user_info of this Verifier.


        :param user_info: The user_info of this Verifier.
        :type user_info: User
        """

        self._user_info = user_info

    @property
    def location_id(self) -> int:
        """Gets the location_id of this Verifier.

        The id of the location this verifier is assigned to  # noqa: E501

        :return: The location_id of this Verifier.
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id: int):
        """Sets the location_id of this Verifier.

        The id of the location this verifier is assigned to  # noqa: E501

        :param location_id: The location_id of this Verifier.
        :type location_id: int
        """

        self._location_id = location_id
