# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Choice(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, question_id: int=None, option_id: int=None):  # noqa: E501
        """Choice - a model defined in Swagger

        :param question_id: The question_id of this Choice.  # noqa: E501
        :type question_id: int
        :param option_id: The option_id of this Choice.  # noqa: E501
        :type option_id: int
        """
        self.swagger_types = {
            'question_id': int,
            'option_id': int
        }

        self.attribute_map = {
            'question_id': 'question_id',
            'option_id': 'option_id'
        }
        self._question_id = question_id
        self._option_id = option_id

    @classmethod
    def from_dict(cls, dikt) -> 'Choice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The choice of this Choice.  # noqa: E501
        :rtype: Choice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question_id(self) -> int:
        """Gets the question_id of this Choice.

        The id of the question  # noqa: E501

        :return: The question_id of this Choice.
        :rtype: int
        """
        return self._question_id

    @question_id.setter
    def question_id(self, question_id: int):
        """Sets the question_id of this Choice.

        The id of the question  # noqa: E501

        :param question_id: The question_id of this Choice.
        :type question_id: int
        """
        if question_id is None:
            raise ValueError("Invalid value for `question_id`, must not be `None`")  # noqa: E501

        self._question_id = question_id

    @property
    def option_id(self) -> int:
        """Gets the option_id of this Choice.

        The id of the option chosen by the user  # noqa: E501

        :return: The option_id of this Choice.
        :rtype: int
        """
        return self._option_id

    @option_id.setter
    def option_id(self, option_id: int):
        """Sets the option_id of this Choice.

        The id of the option chosen by the user  # noqa: E501

        :param option_id: The option_id of this Choice.
        :type option_id: int
        """
        if option_id is None:
            raise ValueError("Invalid value for `option_id`, must not be `None`")  # noqa: E501

        self._option_id = option_id
