# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, jwt_token: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param jwt_token: The jwt_token of this InlineResponse200.  # noqa: E501
        :type jwt_token: str
        """
        self.swagger_types = {
            'jwt_token': str
        }

        self.attribute_map = {
            'jwt_token': 'jwt_token'
        }
        self._jwt_token = jwt_token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jwt_token(self) -> str:
        """Gets the jwt_token of this InlineResponse200.

        Authentication token for new user  # noqa: E501

        :return: The jwt_token of this InlineResponse200.
        :rtype: str
        """
        return self._jwt_token

    @jwt_token.setter
    def jwt_token(self, jwt_token: str):
        """Sets the jwt_token of this InlineResponse200.

        Authentication token for new user  # noqa: E501

        :param jwt_token: The jwt_token of this InlineResponse200.
        :type jwt_token: str
        """

        self._jwt_token = jwt_token
