# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2008(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, election_id: int=None):  # noqa: E501
        """InlineResponse2008 - a model defined in Swagger

        :param election_id: The election_id of this InlineResponse2008.  # noqa: E501
        :type election_id: int
        """
        self.swagger_types = {
            'election_id': int
        }

        self.attribute_map = {
            'election_id': 'election_id'
        }
        self._election_id = election_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2008':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_8 of this InlineResponse2008.  # noqa: E501
        :rtype: InlineResponse2008
        """
        return util.deserialize_model(dikt, cls)

    @property
    def election_id(self) -> int:
        """Gets the election_id of this InlineResponse2008.

        The id of the election just created  # noqa: E501

        :return: The election_id of this InlineResponse2008.
        :rtype: int
        """
        return self._election_id

    @election_id.setter
    def election_id(self, election_id: int):
        """Sets the election_id of this InlineResponse2008.

        The id of the election just created  # noqa: E501

        :param election_id: The election_id of this InlineResponse2008.
        :type election_id: int
        """

        self._election_id = election_id
