# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.org import Org  # noqa: F401,E501
from swagger_server import util


class NewOrg(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_id: int=None, name: str=None, user_org_id: str=None, verifier_password: str=None):  # noqa: E501
        """NewOrg - a model defined in Swagger

        :param org_id: The org_id of this NewOrg.  # noqa: E501
        :type org_id: int
        :param name: The name of this NewOrg.  # noqa: E501
        :type name: str
        :param user_org_id: The user_org_id of this NewOrg.  # noqa: E501
        :type user_org_id: str
        :param verifier_password: The verifier_password of this NewOrg.  # noqa: E501
        :type verifier_password: str
        """
        self.swagger_types = {
            'org_id': int,
            'name': str,
            'user_org_id': str,
            'verifier_password': str
        }

        self.attribute_map = {
            'org_id': 'org_id',
            'name': 'name',
            'user_org_id': 'user_org_id',
            'verifier_password': 'verifier_password'
        }
        self._org_id = org_id
        self._name = name
        self._user_org_id = user_org_id
        self._verifier_password = verifier_password

    @classmethod
    def from_dict(cls, dikt) -> 'NewOrg':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The new_org of this NewOrg.  # noqa: E501
        :rtype: NewOrg
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_id(self) -> int:
        """Gets the org_id of this NewOrg.

        A unique identifier  # noqa: E501

        :return: The org_id of this NewOrg.
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: int):
        """Sets the org_id of this NewOrg.

        A unique identifier  # noqa: E501

        :param org_id: The org_id of this NewOrg.
        :type org_id: int
        """

        self._org_id = org_id

    @property
    def name(self) -> str:
        """Gets the name of this NewOrg.

        The name of the org  # noqa: E501

        :return: The name of this NewOrg.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NewOrg.

        The name of the org  # noqa: E501

        :param name: The name of this NewOrg.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def user_org_id(self) -> str:
        """Gets the user_org_id of this NewOrg.

        The id of the user within the organization (driver license, passport number, etc...)  # noqa: E501

        :return: The user_org_id of this NewOrg.
        :rtype: str
        """
        return self._user_org_id

    @user_org_id.setter
    def user_org_id(self, user_org_id: str):
        """Sets the user_org_id of this NewOrg.

        The id of the user within the organization (driver license, passport number, etc...)  # noqa: E501

        :param user_org_id: The user_org_id of this NewOrg.
        :type user_org_id: str
        """

        self._user_org_id = user_org_id

    @property
    def verifier_password(self) -> str:
        """Gets the verifier_password of this NewOrg.

        The Password used by id verifiers to log in to RPI  # noqa: E501

        :return: The verifier_password of this NewOrg.
        :rtype: str
        """
        return self._verifier_password

    @verifier_password.setter
    def verifier_password(self, verifier_password: str):
        """Sets the verifier_password of this NewOrg.

        The Password used by id verifiers to log in to RPI  # noqa: E501

        :param verifier_password: The verifier_password of this NewOrg.
        :type verifier_password: str
        """

        self._verifier_password = verifier_password
