# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Org(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, org_id: int=None, name: str=None):  # noqa: E501
        """Org - a model defined in Swagger

        :param org_id: The org_id of this Org.  # noqa: E501
        :type org_id: int
        :param name: The name of this Org.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'org_id': int,
            'name': str
        }

        self.attribute_map = {
            'org_id': 'org_id',
            'name': 'name'
        }
        self._org_id = org_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Org':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The org of this Org.  # noqa: E501
        :rtype: Org
        """
        return util.deserialize_model(dikt, cls)

    @property
    def org_id(self) -> int:
        """Gets the org_id of this Org.

        A unique identifier  # noqa: E501

        :return: The org_id of this Org.
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id: int):
        """Sets the org_id of this Org.

        A unique identifier  # noqa: E501

        :param org_id: The org_id of this Org.
        :type org_id: int
        """

        self._org_id = org_id

    @property
    def name(self) -> str:
        """Gets the name of this Org.

        The name of the org  # noqa: E501

        :return: The name of this Org.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Org.

        The name of the org  # noqa: E501

        :param name: The name of this Org.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
