# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.voting_token import VotingToken  # noqa: F401,E501
from swagger_server import util


class VotingUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, voting_token: str=None, user_org_id: str=None):  # noqa: E501
        """VotingUser - a model defined in Swagger

        :param voting_token: The voting_token of this VotingUser.  # noqa: E501
        :type voting_token: str
        :param user_org_id: The user_org_id of this VotingUser.  # noqa: E501
        :type user_org_id: str
        """
        self.swagger_types = {
            'voting_token': str,
            'user_org_id': str
        }

        self.attribute_map = {
            'voting_token': 'voting_token',
            'user_org_id': 'user_org_id'
        }
        self._voting_token = voting_token
        self._user_org_id = user_org_id

    @classmethod
    def from_dict(cls, dikt) -> 'VotingUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The voting_user of this VotingUser.  # noqa: E501
        :rtype: VotingUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def voting_token(self) -> str:
        """Gets the voting_token of this VotingUser.


        :return: The voting_token of this VotingUser.
        :rtype: str
        """
        return self._voting_token

    @voting_token.setter
    def voting_token(self, voting_token: str):
        """Sets the voting_token of this VotingUser.


        :param voting_token: The voting_token of this VotingUser.
        :type voting_token: str
        """

        self._voting_token = voting_token

    @property
    def user_org_id(self) -> str:
        """Gets the user_org_id of this VotingUser.

        The ID of the user within the organization (School id, Driver License, etc...)  # noqa: E501

        :return: The user_org_id of this VotingUser.
        :rtype: str
        """
        return self._user_org_id

    @user_org_id.setter
    def user_org_id(self, user_org_id: str):
        """Sets the user_org_id of this VotingUser.

        The ID of the user within the organization (School id, Driver License, etc...)  # noqa: E501

        :param user_org_id: The user_org_id of this VotingUser.
        :type user_org_id: str
        """

        self._user_org_id = user_org_id
